services:
  - type: web
    name: workflow-go-server
    region: singapore
    plan: starter
    healthCheckPath: /actuator/health
    buildCommand: docker build -t workflow-go-server .
    startCommand: docker run -p 8081:8081 -v /data:/app/data workflow-go-server
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8081
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dog-d01d11fg127c73e9ehj0-a.singapore-postgres.render.com:5432/workflow_go
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: ysMgwz8z96yLG9DO6KYMWye5XTIp1xcn
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
    disk:
      name: workflow-data
      mountPath: /app/data
      sizeGB: 1
    runtime: docker
