spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workflowgodb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

cloudinary:
  cloud-name: dh4rfryvq
  api-key: 273528986331944
  api-secret: FOqHrApkNVQTlmhBEUYBsrL4zE
  secure: true

logging:
  level:
    org.springframework: INFO
    com.workflowgo: DEBUG
