spring:
  datasource:
    url: jdbc:postgresql://dog-d01d11fg127c73e9ehj0-a.singapore-postgres.render.com:5432/workflow_go
    username: root
    password: ysMgwz8z96yLG9DO6KYMWye5XTIp1xcn
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 568f84172230-nspmfd7nfwsfr7ph2m4gmgp0oev9i.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://workflow-go.com/api/oauth2/callback/google
            scope:
              - email
              - profile

server:
  port: ${SERVER_PORT:8001}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  secure: true

logging:
  level:
    org.springframework: WARN
    com.workflowgo: INFO

app:
  oauth2:
    redirectUri: https://workflow-go.com/auth/google/callback
