spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d01d11fgi27c73e9ohj0-a.singapore-postgresql.render.com:5432/workflow_go}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:yxWgwz8z9GyLQ9DD0KYRWye5XTIp1xcn}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID:568f84172230-nspmfd7nfwsfr7ph2m4gmgp0oev9i.apps.googleusercontent.com}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: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}
            redirect-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI:https://work-flow-go-server.onrender.com/oauth2/callback/google}
            scope:
              - email
              - profile

server:
  port: ${SERVER_PORT:8081}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  secure: true

logging:
  level:
    org.springframework: WARN
    com.workflowgo: INFO

app:
  oauth2:
    redirectUri: ${APP_OAUTH2_REDIRECTURI:https://workflow-go.com/auth/google/callback}
