spring:
  application:
    name: work-flow-go-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/workflowgodb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8001
  servlet:
    context-path: /api

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dh4rfryvq}
  api-key: ${CLOUDINARY_API_KEY:273528986331944}
  api-secret: ${CLOUDINARY_API_SECRET:FOqHrApkNVQTlmhBEUYBsrL4zE}
  secure: true

logging:
  level:
    org.springframework: INFO
    com.workflowgo: DEBUG

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
