spring:
  application:
    name: work-flow-go-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/workflowgodb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:568f84172230-nspmfd7nfwsfr7ph2m4gmgp0oev9i.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

server:
  port: 8081
  servlet:
    context-path: /api

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dh4rfryvq}
  api-key: ${CLOUDINARY_API_KEY:273528986331944}
  api-secret: ${CLOUDINARY_API_SECRET:FOqHrApkNVQTlmhBEUYBsrL4zE}
  secure: true

logging:
  level:
    org.springframework: INFO
    com.workflowgo: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

app:
  auth:
    tokenSecret: ${JWT_SECRET:bd04b7c89bfd96a0f14a997f58f2246c37883f3825dd1a3f3d636f9fb0d386a0}
    tokenExpirationMsec: ${JWT_EXPIRATION:864000000}
    authorizedRedirectUris: ${APP_REDIRECT_URI:http://localhost:3000/oauth2/redirect/google}
    refreshToken: ${APP_REFRESH_TOKEN:1//04HuyQnqic0tDCgYIARAAGAQSNwF-L9Ire3vpuUasohAZMQunPVDSbe0fhBmBxvKEBDX2_sx9WBdRoBOCZ1-73smRI2jHOiqcWag}
    clientId: ${APP_CLIENT_ID:568f84172230-nspmfd7nfwsfr7ph2m4gmgp0oev9i.apps.googleusercontent.com}
    clientSecret: ${APP_CLIENT_SECRET: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}
  cors:
    allowedOrigins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8081}
  email:
    senderEmail: ${EMAIL_SENDER:jhanghongwun0728@gmail.com}
    verificationSubject: ${EMAIL_VERIFICATION_SUBJECT:WorkflowGo Email Verification}
    verificationTemplate: 'Your WorkflowGo verification code is: %s

      This code will expire in %d minutes.

      If you did not request this code, please ignore this email.'
    verificationCodeExpirationMinutes: ${EMAIL_VERIFICATION_EXPIRATION:30}
