-- Drop foreign key constraints first
ALTER TABLE IF EXISTS interview_documents DROP CONSTRAINT IF EXISTS fk9nhsldo7q3p93nvbuao8eoose;

-- Drop the documents table and recreate it with the correct structure
DROP TABLE IF EXISTS documents;

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255),
    url VARCHAR(255) NOT NULL,
    content_type VARCHAR(255),
    size BIGINT,
    content BYTEA,
    created_at TIMESTAMP WITH TIME ZONE,
    user_id BIGINT NOT NULL
);

-- Add foreign key constraint
ALTER TABLE documents ADD CONSTRAINT fkkxttj4tp5le2uth212lu49vny FOREIGN KEY (user_id) REFERENCES users(id);

-- Recreate the interview_documents table constraint
ALTER TABLE IF EXISTS interview_documents ADD CONSTRAINT fk9nhsldo7q3p93nvbuao8eoose FOREIGN KEY (document_id) REFERENCES documents(id);
