-- Drop any existing documents to ensure a clean slate
DROP TABLE IF EXISTS interview_documents CASCADE;
DROP TABLE IF EXISTS documents CASCADE;

-- Recreate the documents table with the correct structure
CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255),
    url VARCHAR(255) NOT NULL,
    content_type VARCHAR(255),
    size BIGINT,
    content OID,
    created_at TIMESTAMP WITH TIME ZONE,
    user_id BIGINT NOT NULL REFERENCES users(id)
);

-- Create the foreign key constraint for interview_documents if it exists
CREATE TABLE IF NOT EXISTS interview_documents (
    interview_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    PRIMARY KEY (interview_id, document_id),
    CONSTRAINT fk9nhsldo7q3p93nvbuao8eoose FOREIGN KEY (document_id) REFERENCES documents(id),
    CONSTRAINT fkfj67rw1rodr9qf4jm5oiiav2i FOREIGN KEY (interview_id) REFERENCES interviews(id)
);
